reference_genome:
    # Paths to the fasta and gtf file - please set these to be your desired files
    # TODO: replace these with your desired locations
    fasta: "/project/itmatlab/index/SALMON-1.9.0_indexes/GRCm38.ensemblv93/Mus_musculus.GRCm38.Ensembl.v93.cdna_ncrna_dna.fa.gz"
    gtf: "/project/itmatlab/index/SALMON-1.9.0_indexes/GRCm38.ensemblv93/Mus_musculus.GRCm38.93.gtf.gz"

# Configuration of the optimization process
optimization:
    # Optimization proceeds in batches with each having a certain number of iterations (BEERS2 runs)
    num_batches: 5
    iters_per_batch: 50
    # Each batch uses the top n performing configurations from previous batches to perturb
    # future batches
    take_top_n: 10

real_sample:
    # The real sample we want to replicate
    # Assumed to be paired end data
    FASTQ_R1: "/home/thobr/for_tom/BEERS_noselect/data_UMI/samples/WT4_PolyA/deduped.R1.fastq.gz"
    FASTQ_R2: "/home/thobr/for_tom/BEERS_noselect/data_UMI/samples/WT4_PolyA/deduped.R2.fastq.gz"
    # NOTE: BAM file needs to be in a write-able location, so that it can be sorted and indexed
    BAM: "/home/thobr/for_tom/BEERS_noselect/data_UMI/samples/WT4_PolyA/deduped.Aligned.out.bam"

